/**
 * tailwind-styled-v4 — Embedded Tailwind Engine
 */

import path from "node:path"
import { loadTailwindConfig } from "./loadTailwindConfig"
import { getAllRoutes, getRouteClasses } from "./routeCssCollector"

export type TailwindEngineMode = "jit" | "build" | "manual"

export interface TailwindEngineOptions {
  mode?: TailwindEngineMode
  cwd?: string
  outputDir?: string
  config?: Record<string, unknown>
  minify?: boolean
}

export interface CssGenerateResult {
  route: string
  css: string
  classes: string[]
  sizeBytes: number
}

export const generateCssForClasses = async (
  classes: string[],
  config?: Record<string, unknown>,
  cwd = process.cwd()
): Promise<string> => {
  try {
    const { compileCssFromClasses } = require("./cssCompiler") as typeof import("./cssCompiler")
    const result = compileCssFromClasses(classes)
    if (result?.css && result.resolvedClasses.length > 0) {
      const resolveRate = result.resolvedClasses.length / classes.length
      if (resolveRate >= 0.5) return result.css
    }
  } catch {
    /* fallback */
  }

  const twConfig = config ?? loadTailwindConfig(cwd)

  try {
    return await generateViaTailwindV4(classes, twConfig, cwd)
  } catch {
    /* not available */
  }

  return generateManualCss(classes)
}

const generateViaTailwindV4 = async (
  classes: string[],
  _config: Record<string, unknown>,
  cwd: string
): Promise<string> => {
  const virtualCss = [
    `@import "tailwindcss";`,
    `@layer utilities {`,
    `  /* Generated by tailwind-styled-v4 */`,
    `}`,
  ].join("\n")

  const postcss = require("postcss")
  const tailwindcss = require("@tailwindcss/postcss")

  const result = await postcss([
    tailwindcss({
      optimize: { minify: false },
    }),
  ]).process(virtualCss, {
    from: path.join(cwd, "virtual.css"),
  })

  return filterCssForClasses(result.css, classes)
}

const generateManualCss = (classes: string[]): string => {
  const { generateAtomicCss, parseAtomicClass } = require("./atomicCss")
  const rules = classes.map((c: string) => parseAtomicClass(c)).filter(Boolean)

  if (rules.length === 0) return ""

  const header = `/* Generated by tailwind-styled-v4 — ${new Date().toISOString()} */\n`
  return header + generateAtomicCss(rules)
}

const filterCssForClasses = (fullCss: string, classes: string[]): string => {
  // Immutable state interface
  interface ParserState {
    inBlock: boolean
    keepBlock: boolean
    braceDepth: number
    kept: string[]
  }

  // Initial state
  const initialState: ParserState = {
    inBlock: false,
    keepBlock: false,
    braceDepth: 0,
    kept: [],
  }

  // Pure function to process a single line
  const processLine = (state: ParserState, line: string): ParserState => {
    // Handle header content (base layer, reset)
    if (line.includes("@layer base") || line.includes("*, *::before")) {
      return { ...state, kept: [...state.kept, line] }
    }

    if (!state.inBlock) {
      const isOurClass = classes.some((cls) => {
        const escaped = cls.replace(/[:/[\].!%]/g, "\\$&")
        return line.includes(`.${escaped}`) || line.includes(`.${cls}`)
      })

      if (isOurClass && line.includes("{")) {
        return {
          inBlock: true,
          keepBlock: true,
          braceDepth: 0,
          kept: [...state.kept, line],
        }
      }
      if (line.includes("{") && !line.trim().startsWith("@")) {
        return {
          inBlock: true,
          keepBlock: false,
          braceDepth: 1,
          kept: state.kept,
        }
      }
      return state
    }

    // Inside a block
    const newBraceDepth = state.braceDepth + (line.includes("{") ? 1 : 0) - (line.includes("}") ? 1 : 0)
    const isClosed = newBraceDepth <= 0

    return {
      inBlock: !isClosed,
      keepBlock: isClosed ? false : state.keepBlock,
      braceDepth: Math.max(0, newBraceDepth),
      kept: state.keepBlock ? [...state.kept, line] : state.kept,
    }
  }

  // Use reduce to process all lines - no mutable state!
  const finalState = fullCss.split("\n").reduce(processLine, initialState)
  return finalState.kept.join("\n")
}

export const generateAllRouteCss = async (
  opts: TailwindEngineOptions = {}
): Promise<CssGenerateResult[]> => {
  const { cwd = process.cwd(), outputDir, config, minify = true } = opts

  const results: CssGenerateResult[] = []
  const routes = getAllRoutes()
  const twConfig = config ?? loadTailwindConfig(cwd)

  for (const route of routes) {
    const classes = Array.from(getRouteClasses(route))
    if (classes.length === 0) continue

    try {
      const rawCss = await generateCssForClasses(classes, twConfig, cwd)
      const css = minify ? minifyCss(rawCss) : rawCss

      results.push({
        route,
        css,
        classes,
        sizeBytes: Buffer.byteLength(css, "utf8"),
      })
    } catch (e) {
      console.warn(`[tailwind-styled-v4] CSS generation failed for route ${route}:`, e)
    }
  }

  if (outputDir) {
    const fs = require("node:fs")
    fs.mkdirSync(outputDir, { recursive: true })

    for (const result of results) {
      const filename = routeToFilename(result.route)
      const filepath = path.join(outputDir, filename)
      fs.mkdirSync(path.dirname(filepath), { recursive: true })
      fs.writeFileSync(filepath, result.css)
    }

    const totalSize = results.reduce((sum, r) => sum + r.sizeBytes, 0)
    console.log(
      `[tailwind-styled-v4] Route CSS generated: ${results.length} routes, ${formatBytes(totalSize)} total`
    )
  }

  return results
}

const routeToFilename = (route: string): string => {
  if (route === "/") return "index.css"
  if (route === "__global") return "_global.css"
  return `${route.replace(/^\//, "").replace(/\//g, "_")}.css`
}

const minifyCss = (css: string): string => {
  return css
    .replace(/\/\*[^*]*\*+([^/*][^*]*\*+)*\//g, "")
    .replace(/\s+/g, " ")
    .replace(/\s*{\s*/g, "{")
    .replace(/\s*}\s*/g, "}")
    .replace(/\s*:\s*/g, ":")
    .replace(/\s*;\s*/g, ";")
    .trim()
}

const formatBytes = (bytes: number): string => {
  if (bytes < 1024) return `${bytes}B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)}KB`
  return `${(bytes / 1024 / 1024).toFixed(1)}MB`
}